import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function Credits() {
  return (
    
    <div className={styles.container}>
      <Head>
        <title>Spatial Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Spatial Project 2021</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/credits">Credits</a>
            </li>
          </ul>
        </div>
      </nav>
      <main className={styles.main}>

        
        <h5 className={styles.title2}>
          Project Done by
        </h5>
        <ul>
        <li>Bipin Dhoddamane Ravi</li>
        <li>Deron Jude Martin</li>
        <li>Sarthak Jain</li>
        <li>Utkarsh Neema</li>
        
        </ul>
        <br/>


      </main>
    </div>
  )
}
